name: ${project.build.finalName}
author: [deathibring, Nyvil]
main: dev.tarvos.xyz.Core
version: ${project.version}
api-version: 1.18
commands:
  addtreelocation:
    description: Generate a tree and save its location.
    permission: tarvos.addtreelocation